language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: Lvh7NnLz2boEu29MvXck9RwdJfQteD8gWd1cMGYAAri3AKWTT0oCUPXPWS/SSSW6HAMF/copcMFgD6pYtWYdYTsA7fH5Pvr73OVj+CplH6MF5D8VVtMuizRRaUyDYJybqeK1L6ALizcmDCt3ieq/jSjFKnxJwzYEioHlEU7np0LZxW4s5RouRsiqLXVwf8jo6npyBAVAATQflsWVniGR24pcEJtaffO/FqQHxtNWeKQxx/tIwZsBLoFHht6om9hqNIknPABvY21Ym/TLZ2+vSxsPjNZVsP3DsmuR2aoS8Y0sWh2lC7xhKqkOdxtL61+PLHHACFAVgglgBBlPOjfJg5QzcG+Qs7jku1YS6cPhOntFtcV62tJCrYbi5+lKCIObhXEP5yRFJlWW9s5A4DzOODS0Phjg5LTvn8FUkySQOzv8ffdrgXJVeJ4c/fXcGHCOPZ/jMXl6NPUMvJacZRhoByc2uyWxnF1mXXsH1gsMZl4Qf0GBrPMu4SvTXu/GX2EnBh21k9EqZlpZPAHYC71jHhQ8EiqBSomC+wlwrbs2/2MMn2duR+9rVJ5BLJ00PoNi0O3CahZxbUpsyR4I+kfvsaVneymhzmsiX/Y5zw8y6XGZRFZANVap53BGiXHmhB9j0jlEvK6GnPXpqgXI76GYiVbu6vdTeDVCgm82f5H08fA=
  app: desolate-cove-61967
  on:
    repo: nikthequik/mongo-shopping-list
